/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Builder: typeof import('./src/components/Builder.vue')['default']
    Card: typeof import('primevue/card')['default']
    Device: typeof import('./src/components/flow/nodes/Device.vue')['default']
    DeviceCard: typeof import('./src/components/DeviceCard.vue')['default']
    DeviceList: typeof import('./src/components/DeviceList.vue')['default']
    DnDnode: typeof import('./src/components/DnDnode.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
  }
}
