name: Testing icx
# specify the events this workflow should run on
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
    - master
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: Jaid/action-npm-install@v1.2.4
      - run: tsc
      
      - name: run tests
        run: npm run tests 
      - name: Vscode release plugin
        uses: JCofman/vscodeaction@v2.0.1
        with:
          args: publish -p ${{ secrets.PUBLISHER_TOKEN }}
