name: Testing icx
# specify the events this workflow should run on
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
    - master
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - name: setup
        uses: actions/checkout@v2
      - name: setup2
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: setup3
        uses: Jaid/action-npm-install@v1.2.4
      - name: compile
        run: tsc
      
      - name: Vscode release plugin
        uses: JCofman/vscodeaction@v2.0.1
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        with:
          args: publish -p $PUBLISHER_TOKEN
