on:
  push:
    branches:
      - master
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g gulp
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "package"
